# Generated by Django 3.1.7 on 2021-04-05 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('kategori_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kategori')),
            ],
        ),
    ]
