# Generated by Django 3.1.7 on 2021-04-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_saver_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.saver')),
                ('username_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
